// packages/@codotype/ui/src/modules/generator/components/GeneratorListItem.vue
<template>
  <div class="card card-body border-light shadow-hover mb-2">
    <div class="row">
      <div class="col-lg-12 d-flex justify-content-between align-items-center">
        <p class="lead mb-0 w-100 d-flex justify-content-between align-items-center">
          <router-link :to="'/generators/' + model.id">
            <img class='generator-icon mr-2' :src="model.icon"/>
            {{ model.label }}
          </router-link>

          <GeneratorGitHubLink class='ml-2' :model="model" />
        </p>

      </div>
      <div class="col-lg-12 mt-2">
        <p class="card-text mb-2">
          {{ model.description }}
        </p>
      </div>
      <div class="col-lg-12 d-flex justify-content-between align-items-center">

        <span class="d-flex">
          <GeneratorTypeTag v-for="tag in model.type_tags" :key="tag" :tag="tag" />
          <GeneratorTechTag v-for="tag in model.tech_tags" :key="tag" :tag="tag" />
          <span class='badge badge-info' v-if="model.self_configuring">Self-Configuring</span>
        </span>

        <span class="d-flex">
          <GeneratorExperienceTag :model="model" v-if="model.experience" />
          <GeneratorVersionTag :model="model" />
        </span>

      </div>
    </div>
  </div>
</template>

<script>
import GeneratorTypeTag from './GeneratorTypeTag'
import GeneratorTechTag from './GeneratorTechTag'
import GeneratorVersionTag from './GeneratorVersionTag'
import GeneratorExperienceTag from './GeneratorExperienceTag'
import GeneratorGitHubLink from './GeneratorGitHubLink'

export default {
  name: 'GeneratorListItem',
  props: {
    model: {
      required: true
    }
  },
  components: {
    GeneratorTypeTag,
    GeneratorTechTag,
    GeneratorVersionTag,
    GeneratorExperienceTag,
    GeneratorGitHubLink
  }
}
</script>

<style type="text/css" scoped>
  .generator-icon {
    max-width: 2rem;
  }
</style>

// packages/@codotype/ui/src/components/generator_card/GeneratorListItem.tsx
import * as React from "react";
import { GeneratorMeta } from "@codotype/core";
import { GeneratorTypeTag } from "./GeneratorTypeTag";
import { GeneratorVersionTag } from "./GeneratorVersionTag";
import { GeneratorExperienceTag } from "./GeneratorExperienceTag";
import { GeneratorGithubLink } from "./GeneratorGithubLink";
import { GeneratorTechTag } from "./GeneratorTechTag";

// // // //

export function GeneratorListItem(props: { generator: GeneratorMeta }) {
    const { generator } = props;
    return (
        <div className="card card-body border-light shadow-hover mb-2">
            <div className="row">
                <div className="col-lg-12 d-flex justify-content-between align-items-center">
                    <p className="lead mb-0 w-100 d-flex justify-content-between align-items-center">
                        <img
                            className="mr-2"
                            style={{ maxWidth: "2rem" }}
                            src={generator.icon}
                        />
                        {generator.label}

                        <GeneratorGithubLink generator={generator} />
                    </p>
                </div>
                <div className="col-lg-12 mt-2">
                    <p className="card-text mb-2">{generator.description}</p>
                </div>
                <div className="col-lg-12 d-flex justify-content-between align-items-center">
                    <span className="d-flex">
                        {generator.typeTags.map((tag: string) => (
                            <GeneratorTypeTag tag={tag} key={tag} />
                        ))}
                        {generator.techTags.map((tag: string) => (
                            <GeneratorTechTag tag={tag} key={tag} />
                        ))}
                        {/* <span className='badge badge-info' v-if="generator.self_configuring">Self-Configuring</span> */}
                    </span>

                    <span className="d-flex">
                        <GeneratorExperienceTag
                            experience={generator.experience}
                        />
                        <GeneratorVersionTag version={generator.version} />
                    </span>
                </div>
            </div>
        </div>
    );
}
