// packages/@codotype/ui/src/modules/generator/components/GeneratorGitHubLink.vue
<template>
  <small class="d-flex flex-row align-items-center text-muted">
    <font-awesome-icon v-if="svg" :icon="['fab', 'github']" class="mr-1" />
    <i class="fab fa-github mr-1" v-else />
    <a class='text-muted' target="_blank" :href="'https://github.com/' + model.github_url">
      {{ model.github_url.split('/')[0] }}
    </a>
  </small>
</template>

<script>
export default {
  props: {
    model: {
      required: true
    },
    svg: {
      required: false
    }
  }
}
</script>

// packages/@codotype/ui/src/components/generator_card/GeneratorGithubLink.tsx
import * as React from "react";
import { GeneratorMeta } from "@codotype/types";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faGithub } from "@fortawesome/free-brands-svg-icons";

// // // //

export function GeneratorGithubLink(props: { generator: GeneratorMeta }) {
    const { generator } = props;
    return (
        <small className="d-flex flex-row align-items-center text-muted">
            {/* <font-awesome-icon v-if="svg" : icon="['fab', 'github']" className="mr-1" /> */}
            <FontAwesomeIcon icon={faGithub} />
            <i className="fab fa-github mr-1" />
            <a
                className="text-muted"
                target="_blank"
                href="'https://github.com/' + model.github_url"
            >
                {generator.homepage}
            </a>
        </small>
    );
}
