// packages/@codotype/react-components/src/components/schema_editor/SchemaNewButton.tsx
import * as React from "react";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faPlus } from "@fortawesome/free-solid-svg-icons";

// // // //

export function SchemaNewButton() {
    return (
        <button className="btn btn-lg btn-primary btn-block mb-2">
            <FontAwesomeIcon className="mr-2" icon={faPlus} />
            New Schema
        </button>
    );
}

// packages/@codotype/ui-deprecated/src/components/BlueprintEditor/components/schema/SchemaNewButton.vue
<template>
  <b-button
    id="new-schema-button"
    block
    variant="primary"
    size="lg"
    class="mb-2"
    @click="$store.dispatch('editor/schema/newModel')"
  >
    <i class="fa fa-fw fa-plus" />
    New Schema
  </b-button>
</template>

<script>
export default {
  name: 'SchemaNewButton'
}
</script>
