// packages/@codotype/ui/src/components/BlueprintEditor/components/attribute/AttributeDatatypeForm.vue
<template>
  <b-row class="mt-2">

    <b-col lg="12">
      <p class="lead mb-0">Datatype</p>
      <small class="form-text text-muted">The <span class="text-success">Datatype</span> describes the data represented by this <strong>Attribute</strong> - this <strong>Codotype Generator</strong> supports <strong>{{filteredDatatypes.length}} </strong><span class="text-success">Datatypes</span>.</small>
      <hr />
    </b-col>

    <b-col lg="12">
      <b-row>
        <AttributeDatatypeChild
          v-for="dt in filteredDatatypes"
          :key="dt.value"
          :opt="dt"
          :val="model.datatype"
          :click="setDatatype"
        />
      </b-row>
    </b-col>
  </b-row>
</template>

<script>
import DATATYPE_META from '@codotype/types/lib/datatype-meta'
import datatypes from '@codotype/types/lib/datatypes'
import AttributeDatatypeChild from './AttributeDatatypeChild'

export default {
  props: {
    generator: {
      required: true
    },
    model: {
      required: true
    }
  },
  data () {
    return {
      DATATYPE_META,
      datatypes,
      datatypeObj: Object.keys(DATATYPE_META).map(dt => DATATYPE_META[dt]),
      filteredDatatypes: this.generator.supportedDatatypes.map(dt => DATATYPE_META[dt])
    }
  },
  components: {
    AttributeDatatypeChild
  },
  methods: {
    setDatatype (datatype) {
      this.model.datatype = datatype
      this.$store.commit('editor/schema/attribute/collection/newModel', this.model)
    }
  }
}
</script>

// packages/@codotype/ui/src/components/attribute_editor/AttributeDatatypeForm.tsx
import * as React from "react";
import { DATATYPE_META, DatatypeMeta, Datatype } from "@codotype/types";
import { DatatypeIcon } from "./DatatypeIcon";

// // // //

interface DatatypeOptionProps {
    active: boolean;
    datatype: DatatypeMeta;
    onClick: (updatedDatatype: Datatype) => void;
}
export function DatatypeOption(props: DatatypeOptionProps) {
    let buttonClassName = "btn btn-outline-dark btn-block text-left";
    if (props.active) {
        buttonClassName += " active";
    }

    return (
        <div className="col-sm-6 my-2">
            <button
                className={buttonClassName}
                onClick={() => {
                    props.onClick(props.datatype.value);
                }}
            >
                <DatatypeIcon
                    className="mr-2"
                    datatype={props.datatype.value}
                />
                <strong>{props.datatype.label}</strong>
                <small className="ml-2">{props.datatype.description}</small>
            </button>
        </div>
    );
}

/**
 * AttributeDatatypeFormProps
 * TODO - annotate remaining props
 */
interface AttributeDatatypeFormProps {
    datatype: Datatype | null;
    supportedDatatypes: Datatype[];
    onChangeDatatype: (updatedDatatype: Datatype) => void;
}

/**
 * AttributeDatatypeForm
 * @param props - see `AttributeDatatypeFormProps`
 */
export function AttributeDatatypeForm(props: AttributeDatatypeFormProps) {
    return (
        <div className="row mt-3">
            <div className="col-lg-12">
                <p className="lead mb-0">Datatype</p>
                <small className="form-text text-muted">
                    The <span className="text-success">Datatype </span>
                    describes the data represented by this&nbsp;
                    <strong>Attribute</strong> - this{" "}
                    <strong>Codotype Generator</strong> supports{" "}
                    <strong>{props.supportedDatatypes.length} </strong>
                    <span className="text-success">Datatypes</span>
                </small>
                <hr />
            </div>

            <div className="col-lg-12">
                <div className="row">
                    {Object.keys(DATATYPE_META)
                        .filter((datatype: string) =>
                            props.supportedDatatypes
                                .map(d => String(d))
                                .includes(datatype),
                        )
                        .map((datatype: string) => {
                            // @ts-ignore
                            const attributeType = DATATYPE_META[datatype];
                            return (
                                <DatatypeOption
                                    key={datatype}
                                    datatype={attributeType}
                                    active={
                                        props.datatype === attributeType.value
                                    }
                                    onClick={props.onChangeDatatype}
                                />
                            );
                        })}
                </div>
            </div>
        </div>
    );
}
