// packages/@codotype/ui/src/components/attribute_editor/AttributeListItem.tsx
import * as React from "react";
import { Draggable } from "react-beautiful-dnd";
import { Dropdown } from "react-bootstrap";
import { AttributeListItemLabel } from "./AttributeListItemLabel";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { DATATYPE_META, Attribute } from "@codotype/types";
import {
    faTrashAlt,
    faPencilAlt,
    faEllipsisH,
    faLock,
} from "@fortawesome/free-solid-svg-icons";
import styled from "styled-components";

// // // //

// TODO - migrate this CSS to JS alternative
// .dropdown.no-caret {
//     .dropdown-toggle.btn.btn-sm {
//         &:after {
//             display: none;
//         }
//     }
// }

// // // //

// interface AttributeListItemProps {
//     attribute: Attribute;
//     onEditButtonClick: (attributeToBeEdited: Attribute) => void;
//     onRemoveButtonClick: (attributeToBeRemoved: Attribute) => void;
// }

{
    /* <style lang='sass' scoped>
    @import '../../../../sass/vendor.sass'

    .list-group-item
      padding: 0.25rem 0.5rem
      border-left: 3px solid $gray-500 !important
      cursor: grab

      </style> */
}

const StyledListItem = styled.li`
    cursor: pointer;
    border-left: 3px solid #adb5bd !important;

    &:hover {
        .controls {
            opacity: 1;
        }
    }

    .controls {
        transition: opacity 0.25s ease-in;
        opacity: 0;
        .dropdown-toggle.btn.btn-sm {
            &:after {
                display: none;
            }
        }
    }
`;

/**
 * AttributeListItem
 * @param props.attribute
 * @param props.index
 * @param onClickEdit
 * @param onClickDelete
 */
export function AttributeListItem(props: {
    attribute: Attribute;
    index: number;
    onClickEdit: (attributeToBeEdited: Attribute) => void;
    onClickDelete: (attributeToDelete: Attribute) => void;
}) {
    const { attribute } = props;
    return (
        <Draggable draggableId={String(props.attribute.id)} index={props.index}>
            {provided => (
                <StyledListItem
                    className="list-group-item list-group-item-action py-0 px-2"
                    ref={provided.innerRef}
                    {...provided.draggableProps}
                    {...provided.dragHandleProps}
                >
                    <div className="row d-flex align-items-center">
                        <div className="col-sm-10">
                            <AttributeListItemLabel
                                attribute={props.attribute}
                                datatype={
                                    // @ts-ignore
                                    DATATYPE_META[props.attribute.datatype]
                                }
                            />
                        </div>

                        {props.attribute.locked && (
                            <div
                                className="col-sm-2 text-right controls justify-content-end"
                                v-if="item.locked"
                            >
                                <span
                                    className=" badge badge-secondary"
                                    // v-b-tooltip.hover.right
                                    title="Attribute may not be edited or removed"
                                >
                                    {/* <i className="fa fa-fw fa-lock" /> */}
                                    <FontAwesomeIcon icon={faLock} />
                                </span>
                            </div>
                        )}

                        {!props.attribute.locked && (
                            <div className="col-sm-2 text-right controls">
                                <Dropdown alignRight>
                                    <Dropdown.Toggle
                                        variant="light"
                                        size="sm"
                                        className="rounded px-0 py-0 d-flex"
                                        id={`attribute-${props.attribute.id}-list-item`}
                                    >
                                        <FontAwesomeIcon icon={faEllipsisH} />
                                    </Dropdown.Toggle>

                                    <Dropdown.Menu>
                                        <Dropdown.Item
                                            onClick={() => {
                                                props.onClickEdit(attribute);
                                            }}
                                        >
                                            <FontAwesomeIcon
                                                className="mr-2"
                                                icon={faPencilAlt}
                                            />
                                            Edit
                                        </Dropdown.Item>
                                        <Dropdown.Item
                                            onClick={() => {
                                                props.onClickDelete(attribute);
                                            }}
                                        >
                                            <FontAwesomeIcon
                                                className="mr-2"
                                                icon={faTrashAlt}
                                            />
                                            Delete
                                        </Dropdown.Item>
                                    </Dropdown.Menu>
                                </Dropdown>
                            </div>
                        )}
                    </div>
                </StyledListItem>
            )}
        </Draggable>
    );
}

// packages/ui/src/components/BlueprintEditor/components/attribute/AttributeListItem.vue
<template>
  <b-list-group-item>

    <!--  -->
    <!--  -->
    <!--  -->
    <div class="row d-flex align-items-center">

      <!-- Handle for re-ordering attributes -->
      <div class="col-lg-1 col-sm-4 text-left d-flex align-items-center">
        <i class="fa fa-lg fa-fw fa-bars mr-3" style='cursor: grab;'></i>
        <i class="fa fa-fw text-primary fa-eye mr-3" v-if="item.order === 0"  v-b-tooltip.hover.left title='Leading attribute'></i>
      </div>

      <div class="col-lg-5 col-sm-4">
        <AttributeListItemLabel :item="item"/>
      </div>

      <div class="col-lg-3 col-sm-4">
        <!-- REQUIRED -->
        <!-- <span class="badge" v-if="item.required" v-b-tooltip.hover.top title="Required"> -->
          <!-- <i class="fa fa-asterisk text-danger"></i> -->
        <!-- </span> -->

        <!-- UNIQUE Badge -->
        <span
          v-if="item.unique"
          title="Unique"
          class="badge badge-light"
          v-b-tooltip.hover.top
        >
          <i class="fas fa-snowflake text-dark"></i>
          Unique
        </span>

      </div>

      <div class="col-lg-3 col-sm-4 text-right controls" v-if="item.locked">
        <b-badge
          variant="secondary"
          size="sm"
          v-b-tooltip.hover.left
          title="Locked attributes may not be edited or removed - they are required for correct baseline functionality."
        >
          <i class="fa fa-fw fa-lock"></i>
          Locked
        </b-badge>
      </div>

      <div class="col-lg-3 col-sm-8 text-right controls" v-else>

        <b-button
          size="sm"
          title="Edit"
          variant="outline-warning"
          v-b-tooltip.hover.top
          @click="editModel"
        >
          <i class="fas fa-fw fa-pencil-alt"></i>
        </b-button>

        <b-button
          size="sm"
          title="Remove"
          variant="outline-danger"
          v-b-tooltip.hover.top
          @click="destroyModel()"
        >
          <i class="fa fa-fw fa-trash"></i>
        </b-button>

      </div>

    </div>
    <!--  -->
    <!--  -->
    <!--  -->



  </b-list-group-item>
</template>

<script>
import { mapMutations, mapActions } from 'vuex'
import AttributeListItemLabel from './AttributeListItemLabel'

export default {
  name: 'AttributeListItem',
  props: {
    item: {
      required: true
    }
  },
  components: {
    AttributeListItemLabel
  },
  methods: {
    ...mapMutations({
      setEditModel: 'editor/schema/attribute/collection/editModel',
      showEditModal: 'editor/schema/attribute/modals/edit/showing',
    }),
    ...mapActions({
      removeModel: 'editor/schema/attribute/collection/destroy',
      updateAttributes: 'editor/schema/updateAttributes'
    }),
    editModel () {
      this.setEditModel(this.item)
      this.showEditModal(true)
    },
    destroyModel () {
      this.removeModel(this.item.id)
      this.updateAttributes()
    }
  }
}
</script>

<!-- TODO - move some of this into AttributeLabel component -->
<style lang='sass' scoped>
  .list-group-item
    // border-left: .25rem solid #666666

  .list-group-item:hover i.fa-bars
    opacity: 1

  .list-group-item:hover .controls
    opacity: 1

  i.fa-bars
    transition: opacity .25s ease-in
    opacity: 0

  .badge
    font-weight: 300
    padding: .3rem .3rem

    &.bordered
      border: 1px solid

  .controls
    transition: opacity .25s ease-in
    opacity: 0

</style>
