// packages/@codotype/ui/src/components/BlueprintEditor/components/schema/SchemaPreview.vue
<template>
  <b-row>
    <b-col sm=12>
      <p class="mb-0 text-muted" id="schema-preview">
        <span class="d-flex align-items-center justify-content-between mb-1">
          <span>
            <i class="fa fa-eye mr-2"></i>
            <strong class="m-0">Preview</strong>
          </span>

          <i class="fa fa-info-circle" v-b-tooltip.left.hover="`The data structure of a single ${model.label} Schema`"></i>
        </span>

        <small class="mb-0 text-muted">
          <pre class="rounded bg-dark text-light px-3 py-2">{{ previewBody }}</pre>
        </small>
      </p>
    </b-col>
  </b-row>
</template>

<script>
import { mapGetters } from 'vuex'

export default {
  name: 'SchemaPreview',
  computed: {
    ...mapGetters({
      model: 'editor/schema/selectedModel',
      defaultObject: 'editor/schema/defaultObject'
    }),
    previewBody () {
      return `${this.model.identifier} = new ${this.model.class_name}(` + JSON.stringify(this.defaultObject, null, 2) + ')'
    }
  }
}
</script>

// packages/@codotype/react-components/src/components/schema_editor/SchemaPreview.tsx
import * as React from "react";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faEye } from "@fortawesome/free-solid-svg-icons";
import { InfoTooltip } from "../info_tooltip";
import { Schema } from "../types";

// // // //

/**
 * SchemaPreview
 */
export function SchemaPreview(props: { schema: Schema }) {
    const obj = {
        label: "string",
        score: 0,
    };

    return (
        <div className="row">
            <div className="col-lg-12">
                <p className="mb-0 text-muted">
                    <span className="d-flex align-items-center justify-content-between mb-1 mx-1">
                        <span>
                            <FontAwesomeIcon className="mr-2" icon={faEye} />
                            <strong className="m-0">Preview</strong>
                        </span>
                        <InfoTooltip
                            id="schema-preview"
                            placement="left"
                            message={`The data structure of a single ${props.schema.tokens.label} Schema`}
                        />
                    </span>
                    <small className="mb-0 text-muted">
                        <pre className="rounded bg-dark text-light px-3 py-2">
                            {JSON.stringify(obj, null, 4)}
                        </pre>
                    </small>
                </p>
            </div>
        </div>
    );
}
