// packages/@codotype/ui-deprecated/src/components/BlueprintEditor/components/schema/SchemaIncomingRelations.vue
<template>
  <b-row>
    <b-col lg=12>

      <p class="mb-1 mx-1 text-muted d-flex justify-content-between">
        <span>
          <i class="fa fa-link mr-2" />
          <strong>Incoming Relations</strong>
        </span>
        <i class="fa fa-info-circle" v-b-tooltip.left.hover="`Relations which reference the ${model.label} Schema`" />
      </p>

      <ul class="list-group">

        <b-list-group-item class="text-center" v-if="!reverse_relations[0]">
          <strong class="mb-0 mt-1 text-muted">No Incoming Relations</strong>
          <br>
          <small class="text-muted">Relations which reference the {{ model.label }} Schema</small>
        </b-list-group-item>

        <li class="list-group-item" v-for="rel in reverse_relations" v-else>
          <small>
            <RelationBadge slim direction="in" :model="rel" />
          </small>
        </li>
      </ul>

    </b-col>
  </b-row>

</template>

<script>
import { mapGetters } from 'vuex'
import RelationBadge from '../relation/RelationBadge'

export default {
  name: 'SchemaIncomingRelations',
  components: {
    RelationBadge
  },
  computed: {
    ...mapGetters({
      model: 'editor/schema/selectedModel',
      inflatedSelectedModel: 'editor/schema/inflatedSelectedModel',
      schemas: 'editor/schema/collection/items'
    }),
    reverse_relations () {
      return this.inflatedSelectedModel.reverse_relations
    }
  }
}
</script>

<style lang='sass' scoped>
  li.list-group-item
    padding: 0.25rem 0.5rem
</style>

// packages/@codotype/ui/src/components/SchemaEditor/SchemaIncomingRelations.tsx
import * as React from "react";
import { Schema, UUID } from "@codotype/core";
import { RelationBadge } from "../RelationEditor/RelationBadge";
import { InfoTooltip } from "../InfoTooltip";
import { OverlayTrigger, Tooltip } from "react-bootstrap";

// // // //

interface SchemaIncomingRelationsProps {
    inflatedSchema: Schema;
    onSelectSchema: (nextSelectedSchemaId: UUID) => void;
}

/**
 * SchemaIncomingRelations
 * @param props - see `SchemaIncomingRelationsProps`
 */
export function SchemaIncomingRelations(props: SchemaIncomingRelationsProps) {
    const { inflatedSchema } = props;

    return (
        <div className="row mt-3">
            <div className="col-lg-12">
                <p className="mb-0 text-muted">
                    <span className="d-flex align-items-center justify-content-between mb-1">
                        <strong className="m-0">Incoming Relations</strong>
                        <InfoTooltip
                            id="schema-incoming-relations"
                            placement="left"
                            message={`Relations which reference the ${inflatedSchema.identifiers.singular.title} Schema`}
                        />
                    </span>
                </p>
            </div>
            <div className="col-lg-12">
                <ul className="list-group">
                    {inflatedSchema.referencedBy.length === 0 && (
                        <li className="list-group-item">
                            <strong className="mb-0 mt-1 text-muted">
                                No Incoming Relations
                            </strong>
                            <br />
                            <p className="text-muted mb-0">
                                Relations which reference the{" "}
                                {inflatedSchema.identifiers.singular.title}{" "}
                                Schema
                            </p>
                        </li>
                    )}
                    {inflatedSchema.referencedBy.map(r => {
                        return (
                            <OverlayTrigger
                                key={r.id}
                                placement="left"
                                overlay={
                                    <Tooltip id="attribute-editor-header">
                                        {"Jump to \"" +
                                            r.identifiers.source.canonical
                                                .singular.title +
                                            "\" schema"}
                                    </Tooltip>
                                }
                            >
                                <li
                                    className="list-group-item list-group-item-action py-1 px-2"
                                    style={{ cursor: "pointer" }}
                                    key={r.id}
                                    onClick={() => {
                                        props.onSelectSchema(r.sourceSchemaID);
                                    }}
                                >
                                    <RelationBadge
                                        slim
                                        direction="in"
                                        relation={r}
                                    />
                                </li>
                            </OverlayTrigger>
                        );
                    })}
                </ul>
            </div>
        </div>
    );
}
