// packages/@codotype/ui/src/components/generator_card/GeneratorListItem.tsx
import * as React from "react";
import { GeneratorMeta } from "@codotype/core";
import { GeneratorTypeTag } from "./GeneratorTypeTag";
import { GeneratorVersionTag } from "./GeneratorVersionTag";
import { GeneratorExperienceTag } from "./GeneratorExperienceTag";
import { GeneratorGithubLink } from "./GeneratorGithubLink";
import { GeneratorTechTag } from "./GeneratorTechTag";

// // // //

export function GeneratorListItem(props: { generator: GeneratorMeta }) {
    const { generator } = props;
    return (
        <div className="card card-body border-light shadow-hover mb-2">
            <div className="row">
                <div className="col-lg-12 d-flex justify-content-between align-items-center">
                    <p className="lead mb-0 w-100 d-flex justify-content-between align-items-center">
                        <img
                            className="mr-2"
                            style={{ maxWidth: "2rem" }}
                            src={generator.icon}
                        />
                        {generator.label}

                        <GeneratorGithubLink generator={generator} />
                    </p>
                </div>
                <div className="col-lg-12 mt-2">
                    <p className="card-text mb-2">{generator.description}</p>
                </div>
                <div className="col-lg-12 d-flex justify-content-between align-items-center">
                    <span className="d-flex">
                        {generator.typeTags.map((tag: string) => (
                            <GeneratorTypeTag tag={tag} key={tag} />
                        ))}
                        {generator.techTags.map((tag: string) => (
                            <GeneratorTechTag tag={tag} key={tag} />
                        ))}
                        {/* <span className='badge badge-info' v-if="generator.self_configuring">Self-Configuring</span> */}
                    </span>

                    <span className="d-flex">
                        <GeneratorExperienceTag
                            experience={generator.experience}
                        />
                        <GeneratorVersionTag version={generator.version} />
                    </span>
                </div>
            </div>
        </div>
    );
}

// packages/ui/src/modules/generator/components/GeneratorListItem.vue
<template>
  <div class="card card-body border-light shadow-hover mb-2">
    <div class="row">
      <div class="col-lg-12 d-flex justify-content-between align-items-center">
        <p class="lead mb-0 w-100 d-flex justify-content-between align-items-center">

          <button
            v-if="selectMethod"
            @click="selectMethod(model.id)"
            class="btn btn-link pl-0"
            style='text-decoration: none; font-size: 1.5rem'
          >
            <img class='generator-icon' :src="model.icon"/>
            {{ model.label }}
          </button>

          <router-link
            v-else
            :to="'/generators/' + model.id"
          >
            <img class='generator-icon' :src="model.icon"/>
            {{ model.label }}
          </router-link>

          <small class='ml-2'>
            <a class='text-muted' target="_blank" :href="'https://github.com/' + model.github_url">
              <i class="fab fa-github"></i>
              {{ model.github_url.split('/')[0] }}
            </a>
            <span class='badge badge-light text-muted'>{{ model.version }}</span>
            <!-- <span class='badge badge-warning' v-if="model.official">Official</span> -->
          </small>

        </p>

      </div>
      <div class="col-lg-12">
        <p class="card-text mb-2">
          {{ model.description }}
        </p>
        <!-- <MoreInfoLink :url="model.github_url"/> -->
      </div>
      <div class="col-lg-12 d-flex justify-content-between align-items-center">

        <span class="d-flex">
          <span class='badge badge-primary mr-1' v-for="tag in model.type_tags" :key="tag">{{ tag }}</span>
          <span class='badge badge-info' v-if="model.self_configuring">Self-Configuring</span>
          <span class='badge badge-light mr-1' v-for="tag in model.tech_tags" :key="tag">{{ tag }}</span>
        </span>

        <span class="d-flex">
          <span class='badge badge-success mr-1' v-if="model.experience">
            {{ model.experience }}
          </span>
        </span>

      </div>
    </div>
  </div>
</template>

<script>
import MoreInfoLink from '@codotype/ui/src/components/MoreInfoLink'
import { mapActions } from 'vuex'

export default {
  name: 'GeneratorListItem',
  props: ['model', 'selectMethod'],
  components: {
    MoreInfoLink
  },
  methods: mapActions({
    selectGenerator: 'build/addNewStage'
  })
}
</script>

<style type="text/css" scoped>
  .generator-icon {
    max-width: 2rem;
  }
</style>
