// packages/@codotype/ui/src/components/BlueprintEditor/components/relation/RelationDiagram.vue
<template>
  <div class="row d-flex flex-row align-items-center">
    <div class="col-lg-12">
      <span v-if="slim && sourceLabel !== sourceAlias" v-b-tooltip.hover.left :title='`as "${sourceAlias}"`'>
        <i class="fa fa-mask text-primary mr-1" />
      </span>
      <span v-else-if="sourceLabel !== sourceAlias" class="text-primary">(as <i>{{ sourceAlias }}) </i></span>

      <span class='text-primary'>{{ sourceManyOrOne }} <strong>{{ sourceLabel }}</strong><i :class="iconCss"></i></span><span class="text-info">{{ destManyOrOne }} <strong>{{ destLabel }}</strong></span>

      <span v-if="slim && destLabel !== destAlias" v-b-tooltip.hover.right :title='`as "${destAlias}"`'>
        <i class="fa fa-mask text-info ml-1" />
      </span>
      <span v-else-if="destLabel !== destAlias" class="text-info"> (as <i>{{ destAlias }})</i></span>
    </div>
  </div>
</template>

<!-- // // // //  -->

<script>
export default {
  props: {
    direction: {
      required: true,
      type: String
    },
    sourcePlural: {
      required: true,
      type: Boolean,
      default: false
    },
    sourceLabel: {
      required: true,
      type: String
    },
    sourceAlias: {
      required: true,
      type: String
    },
    destPlural: {
      required: true,
      type: Boolean,
      default: false
    },
    destLabel: {
      required: true,
      type: String
    },
    destAlias: {
      required: true,
      type: String
    },
    slim: {
      required: false,
      type: Boolean,
      default: false
    }
  },
  computed: {
    sourceManyOrOne() {
      if (this.sourcePlural) return 'Many'
      return 'One'
    },
    destManyOrOne() {
      if (this.destPlural) return 'Many'
      return 'One'
    },
    iconCss() {
      const css = ['fa', 'fa-fw', 'mx-1']
      if (this.direction === 'out') {
        css.push('fa-arrow-right')
        css.push('text-primary')
      } else {
        css.push('fa-arrow-left')
        css.push('text-info')
      }
      return css.join(' ')
    }
  }
}
</script>

// packages/@codotype/react-components/src/components/relation_editor/RelationDiagram.tsx
import { Relation } from "../types";
import * as React from "react";
import classnames from "classnames";
import {
    faArrowRight,
    faArrowLeft,
    faMask,
} from "@fortawesome/free-solid-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";

// // // //

export interface RelationDiagramProps {
    direction: string;
    sourcePlural: boolean;
    sourceLabel: string;
    sourceAlias: string;
    destPlural: boolean;
    destLabel: string;
    destAlias: string;
    slim: boolean;
}

export function RelationDiagram(props: RelationDiagramProps) {
    const {
        sourcePlural = false,
        sourceAlias,
        sourceLabel,
        direction,
        destPlural = false,
        destLabel,
        destAlias,
        slim = false,
    } = props;

    const sourceManyOrOne = sourcePlural ? "Many" : "One";
    const destManyOrOne = destPlural ? "Many" : "One";

    const iconCss = classnames("mx-1", {
        "text-primary": direction === "out",
        "text-info": direction !== "out",
    });

    const icon = direction === "out" ? faArrowRight : faArrowLeft;

    return (
        <div className="row d-flex flex-row align-items-center">
            <div className="col-lg-12">
                <span className="text-primary">
                    {sourceManyOrOne} <strong>{sourceLabel}</strong>
                    {slim && sourceLabel !== sourceAlias && (
                        // ADD TOOLTIP_LEFT => `as "${sourceAlias}"`
                        <span>
                            <FontAwesomeIcon
                                className="text-primary ml-1"
                                icon={faMask}
                            />
                        </span>
                    )}
                    {!slim && sourceLabel !== sourceAlias && (
                        <span className="text-primary ml-1">
                            (as <i>{sourceAlias})</i>
                        </span>
                    )}
                    <FontAwesomeIcon className={iconCss} icon={icon} />
                </span>

                <span className="text-info">
                    {destManyOrOne} <strong>{destLabel}</strong>
                </span>

                {slim && destLabel !== destAlias && (
                    // TOOLTIP-RIGHT --> as ${destAlias}
                    <span>
                        <FontAwesomeIcon
                            className="text-info ml-1"
                            icon={faMask}
                        />
                    </span>
                )}

                {!slim && destLabel !== destAlias && (
                    <span className="text-info">
                        {" "}
                        (as <i>{destAlias})</i>
                    </span>
                )}
            </div>
        </div>
    );
}
