// packages/@codotype/ui/src/components/BlueprintEditor/components/attribute/AttributeListItemLabel.vue
<template>
  <small>
    <i :class="'mr-1 fa-fw ' + icon" v-b-tooltip.hover.left :title='tooltip' />
    {{item.label}}
    <span class='text-danger' v-if="item.required">*</span>

    <b-badge
      v-if="index === 0"
      class='ml-2'
      variant="light"
      title="Title Attribute"
      v-b-tooltip.hover.right
    >
      <i class="fa text-primary fa-tag" />
    </b-badge>

    <b-badge
      v-if="item.unique"
      class='ml-2'
      variant="light"
      title="Unique"
      v-b-tooltip.hover.right
    >
      <i class="fas fa-snowflake" />
    </b-badge>
  </small>
</template>

<script>
import DATATYPE_META from '@codotype/types/lib/datatype-meta'

export default {
  name: 'AttributeListItemLabel',
  props: {
    item: {
      required: true
    },
    index: {
      required: true
    }
  },
  computed: {
    icon () {
      return DATATYPE_META[this.item.datatype].icon
    },
    tooltip () {
      return DATATYPE_META[this.item.datatype].label
    }
  }
}
</script>

<style lang='sass'>

  .badge
    font-weight: 300
    padding: .3rem .3rem

</style>

// packages/@codotype/generator-editor/components/attribute_editor/AttributeListItemLabel.tsx
import { DatatypeMeta, Attribute } from "@codotype/types";
import * as React from "react";

interface AttributeListItemLabelProps {
  attribute: Attribute;
  datatype: DatatypeMeta;
}

export function AttributeListItemLabel(props: AttributeListItemLabelProps) {
  return (
    <small>
        <i className={"mr-1 fa-fw " + props.datatype.icon} title={props.datatype.label} />
        {props.attribute.label }
      <span className='text-danger' v-if="item.required">*</span>

      {/* <b-badge
        v-if="index === 0"
        className='ml-2'
        variant="light"
        title="Title Attribute"
        v-b-tooltip.hover.right
    >
      <i class="fa text-primary fa-tag" />
    </b-badge> */}

    { true && (
      <span
        title="Unique"
        // v-b-tooltip.hover.right
        className="ml-2 badge badge-light"
      >
        <i className="fas fa-snowflake" />
        Unique
      </span>
    )}

    </small >
  );
}
