// packages/@codotype/ui/src/components/RelationEditor/RelationDiagram.tsx
import { Relation } from "@codotype/core";
import * as React from "react";
import classnames from "classnames";
import {
    faArrowRight,
    faArrowLeft,
    faMask,
} from "@fortawesome/free-solid-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { OverlayTrigger, Tooltip } from "react-bootstrap";

// // // //

export interface RelationDiagramProps {
    direction: "in" | "out";
    sourcePlural: boolean;
    sourceLabel: string;
    sourceAlias: string;
    destPlural: boolean;
    destLabel: string;
    destAlias: string;
    slim: boolean;
}

export function RelationDiagram(props: RelationDiagramProps) {
    const {
        sourcePlural = false,
        sourceAlias,
        sourceLabel,
        direction,
        destPlural = false,
        destLabel,
        destAlias,
        slim = false,
    } = props;

    const sourceManyOrOne = sourcePlural ? "Many" : "One";
    const destManyOrOne = destPlural ? "Many" : "One";

    const iconCss = classnames("mx-1", {
        "text-primary": direction === "out",
        "text-info": direction !== "out",
    });

    const textColor = classnames({
        "text-primary": direction === "out",
        "text-info": direction !== "out",
    });

    const oppositeTextColor = classnames({
        "text-primary": direction !== "out",
        "text-info": direction === "out",
    });

    const icon = direction === "out" ? faArrowRight : faArrowLeft;

    const source = (
        <span className={textColor}>
            {sourceManyOrOne} <strong>{sourceAlias}</strong>
            {slim && sourceLabel !== sourceAlias && (
                <OverlayTrigger
                    placement="top"
                    overlay={
                        <Tooltip id={`edit-button-tooltip`}>
                            References <strong>{sourceLabel}</strong> Schema
                        </Tooltip>
                    }
                >
                    <FontAwesomeIcon
                        className={classnames("ml-1", textColor)}
                        icon={faMask}
                    />
                </OverlayTrigger>
            )}
            {!slim && sourceLabel !== sourceAlias && (
                <span className={classnames("ml-1", textColor)}>
                    (as <i>{sourceLabel})</i>
                </span>
            )}
        </span>
    );

    const dest = (
        <React.Fragment>
            <span className={oppositeTextColor}>
                {destManyOrOne} <strong>{destAlias}</strong>
            </span>

            {slim && destLabel !== destAlias && (
                <OverlayTrigger
                    placement="top"
                    overlay={
                        <Tooltip id={`edit-button-tooltip`}>
                            References <strong>{destLabel}</strong> Schema
                        </Tooltip>
                    }
                >
                    <FontAwesomeIcon
                        className={classnames("ml-1", oppositeTextColor)}
                        icon={faMask}
                    />
                </OverlayTrigger>
            )}

            {!slim && destLabel !== destAlias && (
                <span className={oppositeTextColor}>
                    {" "}
                    (as <i>{destLabel})</i>
                </span>
            )}
        </React.Fragment>
    );

    return (
        <div className="row d-flex flex-row align-items-center">
            <div className="col-lg-12">
                {props.direction === "out" && source}
                {props.direction === "in" && dest}
                <FontAwesomeIcon className={iconCss} icon={icon} />
                {props.direction === "out" && dest}
                {props.direction === "in" && source}
            </div>
        </div>
    );
}

// packages/@codotype/ui-deprecated/src/components/BlueprintEditor/components/relation/RelationDiagram.vue
<template>
  <div class="row d-flex flex-row align-items-center">
    <div class="col-lg-12">

      <span class='text-primary'>
        {{ sourceManyOrOne }}
        <strong>{{ sourceLabel }}</strong>

          <span
            v-if="slim && sourceLabel !== sourceAlias"
            v-b-tooltip.hover.left
            :title='`as "${sourceAlias}"`'
          >
            <i class="fa fa-mask text-primary ml-1" />
          </span>

          <span
            v-else-if="sourceLabel !== sourceAlias"
            class="text-primary"
          >
            (as <i>{{ sourceAlias }}) </i>
          </span>

          <i :class="iconCss" />
      </span>

      <span class="text-info">{{ destManyOrOne }} <strong>{{ destLabel }}</strong></span>

      <span v-if="slim && destLabel !== destAlias" v-b-tooltip.hover.right :title='`as "${destAlias}"`'>
        <i class="fa fa-mask text-info ml-1" />
      </span>
      <span v-else-if="destLabel !== destAlias" class="text-info"> (as <i>{{ destAlias }})</i></span>

    </div>
  </div>
</template>

<!-- // // // //  -->

<script>
export default {
  props: {
    direction: {
      required: true,
      type: String
    },
    sourcePlural: {
      required: true,
      type: Boolean,
      default: false
    },
    sourceLabel: {
      required: true,
      type: String
    },
    sourceAlias: {
      required: true,
      type: String
    },
    destPlural: {
      required: true,
      type: Boolean,
      default: false
    },
    destLabel: {
      required: true,
      type: String
    },
    destAlias: {
      required: true,
      type: String
    },
    slim: {
      required: false,
      type: Boolean,
      default: false
    }
  },
  computed: {
    sourceManyOrOne() {
      if (this.sourcePlural) return 'Many'
      return 'One'
    },
    destManyOrOne() {
      if (this.destPlural) return 'Many'
      return 'One'
    },
    iconCss() {
      const css = ['fa', 'fa-fw', 'mx-1']
      if (this.direction === 'out') {
        css.push('fa-arrow-right')
        css.push('text-primary')
      } else {
        css.push('fa-arrow-left')
        css.push('text-info')
      }
      return css.join(' ')
    }
  }
}
</script>
