// packages/@codotype/react-components/src/components/relation_editor/RelationBadge.tsx
import { Relation, Schema } from "@codotype/types";
import * as React from "react";
import { RelationDiagram } from "./RelationDiagram";
// import { inflateRelation } from "@codotype/util";

// // // //

export interface RelationBadgeProps {
    direction: "in" | "out";
    relation: Relation;
    slim: boolean;
    selectedSchema: Schema;
    schemas: Schema[];
}

export function RelationBadge(props: RelationBadgeProps) {
    const { slim = false, direction, selectedSchema, relation } = props;

    // const model = inflateRelation({
    //     relation: relation,
    //     schemas: schemas,
    // });

    const model = {
        type: "RELATION_TYPE_BELONGS_TO",
    };

    return (
        <React.Fragment>
            {model.type === "RELATION_TYPE_BELONGS_TO" && (
                <RelationDiagram
                    direction={"direction"}
                    sourcePlural={true}
                    sourceLabel={selectedSchema.tokens.label_plural}
                    sourceAlias={"inflated.reverse_alias.label_plural"}
                    destPlural={false}
                    destLabel={"inflated.schema.label"}
                    destAlias={"inflated.alias.label"}
                    slim={props.slim}
                />
            )}

            {model.type === "RELATION_TYPE_HAS_ONE" && (
                <RelationDiagram
                    direction={"direction"}
                    sourcePlural={false}
                    sourceLabel={selectedSchema.tokens.label}
                    sourceAlias={"inflated.reverse_alias.label"}
                    destPlural={false}
                    destLabel={"inflated.schema.label"}
                    destAlias={"inflated.alias.label"}
                    slim={props.slim}
                />
            )}

            {model.type === "RELATION_TYPE_HAS_AND_BELONGS_TO_MANY" && (
                <RelationDiagram
                    direction={"direction"}
                    sourcePlural={false}
                    sourceLabel={selectedSchema.tokens.label}
                    sourceAlias={"inflated.reverse_alias.label"}
                    destPlural={true}
                    destLabel={"inflated.schema.label_plural"}
                    destAlias={"inflated.alias.label_plural"}
                    slim={props.slim}
                />
            )}

            {model.type === "RELATION_TYPE_HAS_AND_BELONGS_TO_MANY" && (
                <RelationDiagram
                    direction={"direction"}
                    sourcePlural={true}
                    sourceLabel={selectedSchema.tokens.label_plural}
                    sourceAlias={"inflated.reverse_alias.label_plural"}
                    destPlural={true}
                    destLabel={"inflated.schema.label_plural"}
                    destAlias={"inflated.alias.label_plural"}
                    slim={props.slim}
                />
            )}
        </React.Fragment>
    );
}

// packages/@codotype/ui/src/components/BlueprintEditor/components/relation/RelationBadge.vue
<template>
    <RelationDiagram
      v-if="model.type === RELATION_TYPE_BELONGS_TO"
      :direction="direction"
      :sourcePlural="true"
      :sourceLabel="selectedSchema.label_plural"
      :sourceAlias="inflated.reverse_alias.label_plural"
      :destPlural="false"
      :destLabel="inflated.schema.label"
      :destAlias="inflated.alias.label"
      :slim="slim"
    />

    <RelationDiagram
      v-else-if="model.type === RELATION_TYPE_HAS_ONE"
      :direction="direction"
      :sourcePlural="false"
      :sourceLabel="selectedSchema.label"
      :sourceAlias="inflated.reverse_alias.label"
      :destPlural="false"
      :destLabel="inflated.schema.label"
      :destAlias="inflated.alias.label"
      :slim="slim"
    />

    <RelationDiagram
      v-else-if="model.type === RELATION_TYPE_HAS_MANY"
      :direction="direction"
      :sourcePlural="false"
      :sourceLabel="selectedSchema.label"
      :sourceAlias="inflated.reverse_alias.label"
      :destPlural="true"
      :destLabel="inflated.schema.label_plural"
      :destAlias="inflated.alias.label_plural"
      :slim="slim"
    />
</template>

<!-- // // // //  -->

<script>
import { mapGetters } from 'vuex'
import inflateMeta from '@codotype/util/lib/inflateMeta'
import { inflateRelation } from '@codotype/util/lib/inflate'
import RELATION_TYPES from '@codotype/types/lib/relation-types'
import RelationDiagram from './RelationDiagram'

export default {
  props: {
    model: {
      required: true
    },
    direction: {
      required: false,
      type: String,
    },
    slim: {
      required: false,
      type: Boolean,
      default: false
    }
  },
  components: {
    RelationDiagram
  },
  data () {
    return {
      RELATION_TYPE_HAS_ONE: RELATION_TYPES.RELATION_TYPE_HAS_ONE,
      RELATION_TYPE_BELONGS_TO: RELATION_TYPES.RELATION_TYPE_BELONGS_TO,
      RELATION_TYPE_HAS_MANY: RELATION_TYPES.RELATION_TYPE_HAS_MANY
    }
  },
  computed: {
    ...mapGetters({
      allSchemas: 'editor/schema/collection/items',
      selectedSchema: 'editor/schema/selectedModel'
    }),
    selectedRelatedSchema () {
      return this.allSchemas.find(m => m.id === this.model.related_schema_id)
    },
    inflated () {
      this.model.schema_id = this.selectedSchema.id
      return inflateRelation({
        relation: this.model,
        schemas: this.$store.getters['editor/schema/collection/items']
      })
    }
  }
}
</script>
<!--
<style scoped>
  p.large {
    font-size: 1.5rem;
  }
</style> -->
