// packages/@codotype/ui/src/pages/about/AboutJumbotron.tsx
import * as React from "react";

// // // //

/**
 * AboutJumbotron
 */
export function AboutJumbotron() {
    return (
        <div className="row mt-4">
            <div className="col-lg-12 text-center">
                <img
                    className="mb-2"
                    width="100px"
                    height="100px"
                    src="https://res.cloudinary.com/codotype/image/upload/v1560045005/tech-logos/codotype.png"
                />
                <h1 className="display-1">Codotype</h1>
            </div>
        </div>
    );
}

// packages/@codotype/ui/src/components/About/AboutJumbotron.vue
<template>
  <div class="row mt-4">
    <div class="col-lg-12 text-center">
      <img
        class="mb-2"
        width="100px"
        height="100px"
        src="https://res.cloudinary.com/codotype/image/upload/v1560045005/tech-logos/codotype.png"
      />
      <h1 class="display-1">Codotype</h1>
    </div>
  </div>
</template>

<script>
export default {
  name: 'AboutJumbotron'
}
</script>
