// packages/@codotype/ui/src/pages/about/AboutBody.tsx
import * as React from "react";

// // // //

/**
 * AboutBody
 */
export function AboutBody() {
    return (
        <div className="row">
            <div className="col-lg-12 text-center">
                <p className="lead">
                    visual code scaffolding framework for the modern web
                </p>
                <p>Prototype new web applications amazingly fast</p>
                <p>
                    Define your Schemas, Attributes, and Relations - Codotype
                    does the rest
                </p>
            </div>
        </div>
    );
}

// packages/@codotype/ui/src/components/About/AboutBody.vue
<template>
  <div class="row">
    <div class="col-lg-12 text-center">
      <p class="lead">visual code scaffolding framework for the modern web</p>
      <p>Prototype new web applications amazingly fast</p>
      <p>Define your Schemas, Attributes, and Relations - Codotype does the rest</p>
    </div>
  </div>
</template>

<script>
export default {
  name: 'AboutBody'
}
</script>
