// packages/@codotype/ui/src/components/attribute_editor/AttributeListItem.tsx
import * as React from "react";
import { Draggable } from "react-beautiful-dnd";
import { Dropdown } from "react-bootstrap";
import { AttributeListItemLabel } from "./AttributeListItemLabel";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { DATATYPE_META, Attribute } from "@codotype/types";
import {
    faTrashAlt,
    faPencilAlt,
    faEllipsisH,
    faLock,
} from "@fortawesome/free-solid-svg-icons";
import styled from "styled-components";

// // // //

// TODO - migrate this CSS to JS alternative
// .dropdown.no-caret {
//     .dropdown-toggle.btn.btn-sm {
//         &:after {
//             display: none;
//         }
//     }
// }

// // // //

// interface AttributeListItemProps {
//     attribute: Attribute;
//     onEditButtonClick: (attributeToBeEdited: Attribute) => void;
//     onRemoveButtonClick: (attributeToBeRemoved: Attribute) => void;
// }

{
    /* <style lang='sass' scoped>
    @import '../../../../sass/vendor.sass'

    .list-group-item
      padding: 0.25rem 0.5rem
      border-left: 3px solid $gray-500 !important
      cursor: grab

      </style> */
}

const StyledListItem = styled.li`
    cursor: pointer;
    border-left: 3px solid #adb5bd !important;

    &:hover {
        .controls {
            opacity: 1;
        }
    }

    .controls {
        transition: opacity 0.25s ease-in;
        opacity: 0;
        .dropdown-toggle.btn.btn-sm {
            &:after {
                display: none;
            }
        }
    }
`;

/**
 * AttributeListItem
 * @param props.attribute
 * @param props.index
 * @param onClickEdit
 * @param onClickDelete
 */
export function AttributeListItem(props: {
    attribute: Attribute;
    index: number;
    onClickEdit: (attributeToBeEdited: Attribute) => void;
    onClickDelete: (attributeToDelete: Attribute) => void;
}) {
    const { attribute } = props;
    return (
        <Draggable draggableId={String(props.attribute.id)} index={props.index}>
            {provided => (
                <StyledListItem
                    className="list-group-item list-group-item-action py-0 px-2"
                    ref={provided.innerRef}
                    {...provided.draggableProps}
                    {...provided.dragHandleProps}
                >
                    <div className="row d-flex align-items-center">
                        <div className="col-sm-10">
                            <AttributeListItemLabel
                                attribute={props.attribute}
                                datatype={
                                    // @ts-ignore
                                    DATATYPE_META[props.attribute.datatype]
                                }
                            />
                        </div>

                        {props.attribute.locked && (
                            <div
                                className="col-sm-2 text-right controls justify-content-end"
                                v-if="item.locked"
                            >
                                <span
                                    className=" badge badge-secondary"
                                    // v-b-tooltip.hover.right
                                    title="Attribute may not be edited or removed"
                                >
                                    {/* <i className="fa fa-fw fa-lock" /> */}
                                    <FontAwesomeIcon icon={faLock} />
                                </span>
                            </div>
                        )}

                        {!props.attribute.locked && (
                            <div className="col-sm-2 text-right controls">
                                <Dropdown alignRight>
                                    <Dropdown.Toggle
                                        variant="light"
                                        size="sm"
                                        className="rounded px-0 py-0 d-flex"
                                        id={`attribute-${props.attribute.id}-list-item`}
                                    >
                                        <FontAwesomeIcon icon={faEllipsisH} />
                                    </Dropdown.Toggle>

                                    <Dropdown.Menu>
                                        <Dropdown.Item
                                            onClick={() => {
                                                props.onClickEdit(attribute);
                                            }}
                                        >
                                            <FontAwesomeIcon
                                                className="mr-2"
                                                icon={faPencilAlt}
                                            />
                                            Edit
                                        </Dropdown.Item>
                                        <Dropdown.Item
                                            onClick={() => {
                                                props.onClickDelete(attribute);
                                            }}
                                        >
                                            <FontAwesomeIcon
                                                className="mr-2"
                                                icon={faTrashAlt}
                                            />
                                            Delete
                                        </Dropdown.Item>
                                    </Dropdown.Menu>
                                </Dropdown>
                            </div>
                        )}
                    </div>
                </StyledListItem>
            )}
        </Draggable>
    );
}

// packages/@codotype/ui/src/components/BlueprintEditor/components/attribute/AttributeListItem.vue
<template>
  <li class="list-group-item">

    <div class="row d-flex align-items-center">

      <!-- TODO - re-introduce "Leading Attribute", maybe rename? -->
      <!-- <div class="col-sm-1 text-left d-flex align-items-center"> -->
        <!-- <i class="fa fa-fw text-primary fa-eye" v-if="item.order === 0"  v-b-tooltip.hover.left title='Leading attribute'></i> -->
      <!-- </div> -->

      <div class="col-sm-10">
        <AttributeListItemLabel :item="item"/>
      </div>

      <div class="col-sm-2 text-right controls justify-content-end" v-if="item.locked">
        <b-badge
          variant="secondary"
          v-b-tooltip.hover.right
          title="Email attribute may not be edited or removed"
        >
          <i class="fa fa-fw fa-lock"></i>
        </b-badge>
      </div>

      <div class="col-sm-2 text-right controls" v-else>
        <b-dropdown
          right
          no-caret
          size="sm"
          variant="light"
          toggle-class='rounded px-0 py-0 d-flex'
          boundary="viewport"
        >
          <template slot="button-content">
            <!-- <i class="fa fa-fw fa-ellipsis-h"></i> -->
            GO
          </template>

          <b-dropdown-item-button @click="editModel(item)">
            <i class="fas fa-fw fa-pencil-alt"></i>
            Edit
          </b-dropdown-item-button>

          <DestroyButton scope="attribute" :modelId="item.id" />

        </b-dropdown>
      </div>


    </div>

  </li>
</template>

<script>
import { mapMutations, mapActions } from 'vuex'
import AttributeListItemLabel from './AttributeListItemLabel'
import DestroyButton from '../DestroyButton'

export default {
  name: 'AttributeListItem',
  props: {
    item: {
      required: true
    }
  },
  components: {
    AttributeListItemLabel,
    DestroyButton
  },
  methods: mapActions({
    editModel: 'editor/schema/attribute/editModel'
  })
}
</script>

<style lang='sass' scoped>
@import '../../../../sass/vendor.sass'

.list-group-item
  padding: 0.25rem 0.5rem
  border-left: 3px solid $gray-500 !important
  cursor: grab

.list-group-item:hover i.fa-equals
  opacity: 1

.list-group-item:hover .controls
  opacity: 1

.controls
  transition: opacity .25s ease-in
  opacity: 0
</style>
