// packages/@codotype/ui/src/components/attribute_editor/AttributeListItemLabel.tsx
import { DatatypeMeta, Attribute } from "@codotype/types";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faSnowflake } from "@fortawesome/free-solid-svg-icons";
import * as React from "react";
import { DatatypeIcon } from "./DatatypeIcon";
import { OverlayTrigger, Tooltip } from "react-bootstrap";

// // // //

interface AttributeListItemLabelProps {
    attribute: Attribute;
    datatype: DatatypeMeta;
}

export function AttributeListItemLabel(props: AttributeListItemLabelProps) {
    const { attribute } = props;
    return (
        <small>
            {/* DatatypeIcon + Tooltip */}
            <OverlayTrigger
                placement="left"
                overlay={
                    <Tooltip id={`datatype-icon-${attribute.id}`}>
                        {props.datatype.label}
                    </Tooltip>
                }
            >
                <span className="px-1">
                    <DatatypeIcon datatype={attribute.datatype} />
                </span>
            </OverlayTrigger>

            {/* Attribute label */}
            <span className="ml-2">{attribute.label}</span>

            {/* Required badge */}
            {attribute.required && <span className="ml-1 text-danger">*</span>}

            {/* <b-badge
                v-if="index === 0"
                className='ml-2'
                variant="light"
                title="Title Attribute"
                v-b-tooltip.hover.right
            >
              <i class="fa text-primary fa-tag" />
            </b-badge> */}

            {/* Unique badge + tooltip */}
            {attribute.unique && (
                <OverlayTrigger
                    placement="right"
                    overlay={
                        <Tooltip id={`unique-badge-${attribute.id}`}>
                            Unique
                        </Tooltip>
                    }
                >
                    <span className="ml-2 badge badge-light">
                        <FontAwesomeIcon icon={faSnowflake} />
                    </span>
                </OverlayTrigger>
            )}
        </small>
    );
}

// packages/@codotype/ui/src/components/BlueprintEditor/components/attribute/AttributeListItemLabel.vue
<template>
  <small>
    <i :class="'mr-1 fa-fw ' + icon" v-b-tooltip.hover.left :title='tooltip' />
    {{item.label}}
    <span class='text-danger' v-if="item.required">*</span>

    <b-badge
      v-if="index === 0"
      class='ml-2'
      variant="light"
      title="Title Attribute"
      v-b-tooltip.hover.right
    >
      <i class="fa text-primary fa-tag" />
    </b-badge>

    <b-badge
      v-if="item.unique"
      class='ml-2'
      variant="light"
      title="Unique"
      v-b-tooltip.hover.right
    >
      <i class="fas fa-snowflake" />
    </b-badge>
  </small>
</template>

<script>
import DATATYPE_META from '@codotype/types/lib/datatype-meta'

export default {
  name: 'AttributeListItemLabel',
  props: {
    item: {
      required: true
    },
    index: {
      required: true
    }
  },
  computed: {
    icon () {
      return DATATYPE_META[this.item.datatype].icon
    },
    tooltip () {
      return DATATYPE_META[this.item.datatype].label
    }
  }
}
</script>

<style lang='sass'>

  .badge
    font-weight: 300
    padding: .3rem .3rem

</style>
